name: VTR Kernel Build (GCC 4.9)

on:
  push:
    branches:
      - kernel-only # S'exécute quand vous poussez sur cette branche
  # Permet de déclencher la compilation manuellement depuis l'onglet Actions
  workflow_dispatch:
    inputs:
        build_info:
          description: "Build triggered manually for VTR Kernel"
          required: false
          default: "Manual run"
          
permissions:
  contents: write

env:
  # --- Variables pour la compilation EMUI 9.0.1 (Hi3660) ---
  KERNEL_SOURCE_DIR: 'kernel'               # L'emplacement du Makefile dans votre dépôt
  ARCH: 'arm64'                              # Architecture cible
  # Prefix basé sur le README: aarch64-linux-android-
  CROSS_COMPILE_PREFIX: 'aarch64-linux-android-' 
  DEFCONFIG: 'merge_hi3660_defconfig'       # Confirmé par le README
  TOOLCHAIN_NAME: 'gcc-4.9'                  # Toolchain requise
  TOOLCHAIN_URL: 'https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9/archive/refs/heads/master.zip'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: kernel-only # Clone la branche spécifique
          submodules: recursive 

      - name: 🛠️ Install Build Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses-dev flex bison bc unzip wget git

      - name: ⬇️ Download & Configure GCC 4.9 Toolchain
        run: |
          echo "Downloading required GCC 4.9 toolchain..."
          # Télécharge et dézippe la toolchain LineageOS GCC 4.9
          wget -q -O toolchain.zip ${{ env.TOOLCHAIN_URL }}
          unzip -q toolchain.zip -d ./
          
          # Le nom du dossier dézippé est long, on le renomme pour plus de simplicité
          TOOLCHAIN_DIR=$(find . -maxdepth 1 -type d -name "android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9*")
          mv $TOOLCHAIN_DIR toolchain
          
          # Ajoute le chemin /bin de la toolchain à la variable PATH (comme dans votre README)
          echo "PATH=$PWD/toolchain/bin:$PATH" >> $GITHUB_ENV
          
      - name: ⚙️ Configure Kernel (defconfig)
        run: |
          cd ${{ env.KERNEL_SOURCE_DIR }}
          # Exécute la commande de configuration spécifique au README
          make O=out ARCH=${{ env.ARCH }} ${{ env.DEFCONFIG }}

      - name: 🔨 Compile Kernel (Multithreaded)
        timeout-minutes: 45
        run: |
          cd ${{ env.KERNEL_SOURCE_DIR }}
          
          # Exécute la commande de compilation spécifique au README
          make -j$(nproc) O=out \
            ARCH=${{ env.ARCH }} \
            CROSS_COMPILE=${{ env.CROSS_COMPILE_PREFIX }}

      - name: 📦 Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-kernel-${{ github.sha }}
          # Chemin de sortie confirmé par votre README
          path: |
            ${{ env.KERNEL_SOURCE_DIR }}/out/arch/${{ env.ARCH }}/boot/Image.gz
            ${{ env.KERNEL_SOURCE_DIR }}/out/arch/${{ env.ARCH }}/boot/Image.gz-dtb # Inclus au cas où
          retention-days: 7
          if-no-files-found: "error"
          
      - name: ✅ Verify Final Output
        run: |
          ls -l ${{ env.KERNEL_SOURCE_DIR }}/out/arch/${{ env.ARCH }}/boot/Image.gz
          echo "Compilation finished. Check Artifacts for Image.gz."
          
