name: Build NetHunter Kernel

on:
  workflow_dispatch:
  push:
    branches: [kernel-only]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bison flex libssl-dev bc libncurses-dev

      - name: Build kernel
        working-directory: kernel
        run: |
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- oldconfig
          make -j$(nproc) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-

      - name: Upload kernel image (Image.gz-dtb)
        uses: actions/upload-artifact@v4
        with:
          name: NetHunter-Image.gz-dtb
          path: kernel/arch/arm64/boot/Image.gz-dtb
